// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gonpe/video/v1/video_api.proto

package videov1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "github.com/haken-anime/gonpe-proto/gen/go/gonpe/pagination/v1"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRecentlyVideosRequest struct {
	Page                 *v1.PagerInput `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListRecentlyVideosRequest) Reset()         { *m = ListRecentlyVideosRequest{} }
func (m *ListRecentlyVideosRequest) String() string { return proto.CompactTextString(m) }
func (*ListRecentlyVideosRequest) ProtoMessage()    {}
func (*ListRecentlyVideosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4a7caa6426bdf00, []int{0}
}

func (m *ListRecentlyVideosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecentlyVideosRequest.Unmarshal(m, b)
}
func (m *ListRecentlyVideosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecentlyVideosRequest.Marshal(b, m, deterministic)
}
func (m *ListRecentlyVideosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecentlyVideosRequest.Merge(m, src)
}
func (m *ListRecentlyVideosRequest) XXX_Size() int {
	return xxx_messageInfo_ListRecentlyVideosRequest.Size(m)
}
func (m *ListRecentlyVideosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecentlyVideosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecentlyVideosRequest proto.InternalMessageInfo

func (m *ListRecentlyVideosRequest) GetPage() *v1.PagerInput {
	if m != nil {
		return m.Page
	}
	return nil
}

type ListRecentlyVideosResponse struct {
	Videos               []*VideoForList `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Page                 *v1.PagerOutput `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListRecentlyVideosResponse) Reset()         { *m = ListRecentlyVideosResponse{} }
func (m *ListRecentlyVideosResponse) String() string { return proto.CompactTextString(m) }
func (*ListRecentlyVideosResponse) ProtoMessage()    {}
func (*ListRecentlyVideosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4a7caa6426bdf00, []int{1}
}

func (m *ListRecentlyVideosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecentlyVideosResponse.Unmarshal(m, b)
}
func (m *ListRecentlyVideosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecentlyVideosResponse.Marshal(b, m, deterministic)
}
func (m *ListRecentlyVideosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecentlyVideosResponse.Merge(m, src)
}
func (m *ListRecentlyVideosResponse) XXX_Size() int {
	return xxx_messageInfo_ListRecentlyVideosResponse.Size(m)
}
func (m *ListRecentlyVideosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecentlyVideosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecentlyVideosResponse proto.InternalMessageInfo

func (m *ListRecentlyVideosResponse) GetVideos() []*VideoForList {
	if m != nil {
		return m.Videos
	}
	return nil
}

func (m *ListRecentlyVideosResponse) GetPage() *v1.PagerOutput {
	if m != nil {
		return m.Page
	}
	return nil
}

type GetVideoRequest struct {
	ShortId              string   `protobuf:"bytes,1,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideoRequest) Reset()         { *m = GetVideoRequest{} }
func (m *GetVideoRequest) String() string { return proto.CompactTextString(m) }
func (*GetVideoRequest) ProtoMessage()    {}
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4a7caa6426bdf00, []int{2}
}

func (m *GetVideoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoRequest.Unmarshal(m, b)
}
func (m *GetVideoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoRequest.Marshal(b, m, deterministic)
}
func (m *GetVideoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoRequest.Merge(m, src)
}
func (m *GetVideoRequest) XXX_Size() int {
	return xxx_messageInfo_GetVideoRequest.Size(m)
}
func (m *GetVideoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoRequest proto.InternalMessageInfo

func (m *GetVideoRequest) GetShortId() string {
	if m != nil {
		return m.ShortId
	}
	return ""
}

type GetVideoResponse struct {
	Video                *Video   `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideoResponse) Reset()         { *m = GetVideoResponse{} }
func (m *GetVideoResponse) String() string { return proto.CompactTextString(m) }
func (*GetVideoResponse) ProtoMessage()    {}
func (*GetVideoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4a7caa6426bdf00, []int{3}
}

func (m *GetVideoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoResponse.Unmarshal(m, b)
}
func (m *GetVideoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoResponse.Marshal(b, m, deterministic)
}
func (m *GetVideoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoResponse.Merge(m, src)
}
func (m *GetVideoResponse) XXX_Size() int {
	return xxx_messageInfo_GetVideoResponse.Size(m)
}
func (m *GetVideoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoResponse proto.InternalMessageInfo

func (m *GetVideoResponse) GetVideo() *Video {
	if m != nil {
		return m.Video
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRecentlyVideosRequest)(nil), "gonpe.video.v1.ListRecentlyVideosRequest")
	proto.RegisterType((*ListRecentlyVideosResponse)(nil), "gonpe.video.v1.ListRecentlyVideosResponse")
	proto.RegisterType((*GetVideoRequest)(nil), "gonpe.video.v1.GetVideoRequest")
	proto.RegisterType((*GetVideoResponse)(nil), "gonpe.video.v1.GetVideoResponse")
}

func init() { proto.RegisterFile("gonpe/video/v1/video_api.proto", fileDescriptor_c4a7caa6426bdf00) }

var fileDescriptor_c4a7caa6426bdf00 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x49, 0xfb, 0xbe, 0x6d, 0x9d, 0x62, 0x95, 0x05, 0xa1, 0x0d, 0x62, 0x43, 0x4f, 0xf5,
	0x0f, 0x5b, 0xd2, 0xf6, 0x2e, 0xf6, 0x60, 0x29, 0x28, 0x86, 0x1c, 0x82, 0x48, 0xa1, 0xc4, 0x76,
	0xa9, 0x8b, 0x9a, 0x5d, 0xb3, 0xdb, 0x80, 0xdf, 0xc0, 0xcf, 0xe1, 0xd1, 0x0f, 0xe2, 0xc1, 0x4f,
	0x25, 0x99, 0x4d, 0x29, 0xc6, 0x06, 0xbc, 0x25, 0x33, 0xbf, 0x79, 0xe6, 0x99, 0x87, 0x85, 0xa3,
	0xa5, 0x88, 0x24, 0xeb, 0x25, 0x7c, 0xc1, 0x44, 0x2f, 0x71, 0xcd, 0xc7, 0x2c, 0x94, 0x9c, 0xca,
	0x58, 0x68, 0x41, 0x1a, 0xd8, 0xa7, 0x58, 0xa6, 0x89, 0x6b, 0xb7, 0x0d, 0x2f, 0xc3, 0x25, 0x8f,
	0x42, 0xcd, 0x45, 0x94, 0x0e, 0xc9, 0x70, 0xc9, 0x62, 0x33, 0x60, 0xdb, 0xdb, 0x04, 0x4d, 0xaf,
	0xe3, 0x41, 0xeb, 0x8a, 0x2b, 0xed, 0xb3, 0x39, 0x8b, 0xf4, 0xd3, 0x6b, 0x90, 0xb6, 0x94, 0xcf,
	0x5e, 0x56, 0x4c, 0x69, 0x32, 0x80, 0x7f, 0xa9, 0x4e, 0xd3, 0x72, 0xac, 0x6e, 0xbd, 0xdf, 0xa6,
	0x66, 0xf1, 0x66, 0x11, 0x4d, 0x5c, 0xea, 0xa5, 0x8b, 0x26, 0x91, 0x5c, 0x69, 0x1f, 0xe1, 0xce,
	0x9b, 0x05, 0xf6, 0x36, 0x49, 0x25, 0x45, 0xa4, 0x18, 0x19, 0x42, 0x05, 0xf7, 0xab, 0xa6, 0xe5,
	0x94, 0xbb, 0xf5, 0xfe, 0x21, 0xfd, 0x79, 0x0e, 0x45, 0xfe, 0x52, 0xc4, 0xa8, 0x91, 0xb1, 0x64,
	0x98, 0x39, 0x29, 0xa1, 0x13, 0xa7, 0xd8, 0xc9, 0xcd, 0x4a, 0x6f, 0xac, 0x9c, 0xc1, 0xde, 0x98,
	0x69, 0x14, 0x5c, 0x9f, 0xd4, 0x82, 0x9a, 0x7a, 0x10, 0xb1, 0x9e, 0xf1, 0x05, 0x9e, 0xb5, 0xe3,
	0x57, 0xf1, 0x7f, 0xb2, 0xe8, 0x9c, 0xc3, 0xfe, 0x86, 0xce, 0xdc, 0x9e, 0xc2, 0x7f, 0x74, 0x90,
	0x45, 0x70, 0xb0, 0xd5, 0xac, 0x6f, 0x98, 0xfe, 0xa7, 0x05, 0x35, 0x2c, 0x5c, 0x78, 0x13, 0xf2,
	0x08, 0xe4, 0x77, 0x0a, 0xe4, 0x38, 0x2f, 0x50, 0x18, 0xbe, 0x7d, 0xf2, 0x17, 0x34, 0xb3, 0x79,
	0x0d, 0xb5, 0xb5, 0x75, 0xd2, 0xce, 0xcf, 0xe5, 0x22, 0xb0, 0x9d, 0x62, 0xc0, 0xc8, 0x8d, 0x02,
	0x20, 0x73, 0xf1, 0x9c, 0xc3, 0x46, 0xbb, 0xe6, 0x36, 0xc9, 0xbd, 0xf4, 0xe5, 0x78, 0xd6, 0x5d,
	0x15, 0x5b, 0x89, 0xfb, 0x5e, 0x2a, 0x8f, 0x83, 0xdb, 0x8f, 0x52, 0x63, 0x8c, 0x03, 0x88, 0xd1,
	0xc0, 0xfd, 0xca, 0x0a, 0x53, 0x2c, 0x4c, 0x03, 0xf7, 0xbe, 0x82, 0x6f, 0x6e, 0xf0, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0xaf, 0x84, 0x54, 0x95, 0xe2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VideoAPIClient is the client API for VideoAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VideoAPIClient interface {
	// Get videos in descending order of recording at.
	ListRecentlyVideos(ctx context.Context, in *ListRecentlyVideosRequest, opts ...grpc.CallOption) (*ListRecentlyVideosResponse, error)
	// Get video details.
	GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*GetVideoResponse, error)
}

type videoAPIClient struct {
	cc *grpc.ClientConn
}

func NewVideoAPIClient(cc *grpc.ClientConn) VideoAPIClient {
	return &videoAPIClient{cc}
}

func (c *videoAPIClient) ListRecentlyVideos(ctx context.Context, in *ListRecentlyVideosRequest, opts ...grpc.CallOption) (*ListRecentlyVideosResponse, error) {
	out := new(ListRecentlyVideosResponse)
	err := c.cc.Invoke(ctx, "/gonpe.video.v1.VideoAPI/ListRecentlyVideos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoAPIClient) GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*GetVideoResponse, error) {
	out := new(GetVideoResponse)
	err := c.cc.Invoke(ctx, "/gonpe.video.v1.VideoAPI/GetVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoAPIServer is the server API for VideoAPI service.
type VideoAPIServer interface {
	// Get videos in descending order of recording at.
	ListRecentlyVideos(context.Context, *ListRecentlyVideosRequest) (*ListRecentlyVideosResponse, error)
	// Get video details.
	GetVideo(context.Context, *GetVideoRequest) (*GetVideoResponse, error)
}

func RegisterVideoAPIServer(s *grpc.Server, srv VideoAPIServer) {
	s.RegisterService(&_VideoAPI_serviceDesc, srv)
}

func _VideoAPI_ListRecentlyVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecentlyVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoAPIServer).ListRecentlyVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gonpe.video.v1.VideoAPI/ListRecentlyVideos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoAPIServer).ListRecentlyVideos(ctx, req.(*ListRecentlyVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoAPI_GetVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoAPIServer).GetVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gonpe.video.v1.VideoAPI/GetVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoAPIServer).GetVideo(ctx, req.(*GetVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VideoAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gonpe.video.v1.VideoAPI",
	HandlerType: (*VideoAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRecentlyVideos",
			Handler:    _VideoAPI_ListRecentlyVideos_Handler,
		},
		{
			MethodName: "GetVideo",
			Handler:    _VideoAPI_GetVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gonpe/video/v1/video_api.proto",
}
