// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gonpe/video/v1/video.proto

package videov1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	v1 "github.com/haken-anime/gonpe-proto/gen/go/gonpe/image/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A video content classification.
type Category int32

const (
	Category_CATEGORY_UNKNOWN     Category = 0
	Category_CATEGORY_ANIMATION   Category = 1
	Category_CATEGORY_MUSIC       Category = 2
	Category_CATEGORY_VARIETY     Category = 3
	Category_CATEGORY_DRAMA       Category = 4
	Category_CATEGORY_CINEMA      Category = 5
	Category_CATEGORY_SPORT       Category = 6
	Category_CATEGORY_INFORMATION Category = 7
	Category_CATEGORY_NEWS        Category = 8
	Category_CATEGORY_DOCUMENTARY Category = 9
	Category_CATEGORY_THEATER     Category = 10
	Category_CATEGORY_HOBBY       Category = 11
	Category_CATEGORY_WELFARE     Category = 12
	Category_CATEGORY_ETC         Category = 13
)

var Category_name = map[int32]string{
	0:  "CATEGORY_UNKNOWN",
	1:  "CATEGORY_ANIMATION",
	2:  "CATEGORY_MUSIC",
	3:  "CATEGORY_VARIETY",
	4:  "CATEGORY_DRAMA",
	5:  "CATEGORY_CINEMA",
	6:  "CATEGORY_SPORT",
	7:  "CATEGORY_INFORMATION",
	8:  "CATEGORY_NEWS",
	9:  "CATEGORY_DOCUMENTARY",
	10: "CATEGORY_THEATER",
	11: "CATEGORY_HOBBY",
	12: "CATEGORY_WELFARE",
	13: "CATEGORY_ETC",
}

var Category_value = map[string]int32{
	"CATEGORY_UNKNOWN":     0,
	"CATEGORY_ANIMATION":   1,
	"CATEGORY_MUSIC":       2,
	"CATEGORY_VARIETY":     3,
	"CATEGORY_DRAMA":       4,
	"CATEGORY_CINEMA":      5,
	"CATEGORY_SPORT":       6,
	"CATEGORY_INFORMATION": 7,
	"CATEGORY_NEWS":        8,
	"CATEGORY_DOCUMENTARY": 9,
	"CATEGORY_THEATER":     10,
	"CATEGORY_HOBBY":       11,
	"CATEGORY_WELFARE":     12,
	"CATEGORY_ETC":         13,
}

func (x Category) String() string {
	return proto.EnumName(Category_name, int32(x))
}

func (Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83e5cd47fcaaecba, []int{0}
}

// A video publishing status.
type Status int32

const (
	Status_STATUS_UNREGISTERED       Status = 0
	Status_STATUS_REGISTERED         Status = 1
	Status_STATUS_PUBLISHED          Status = 2
	Status_STATUS_ARCHIVED           Status = 3
	Status_STATUS_TEMPORARY_RESTORED Status = 4
	Status_STATUS_SUSPENDED          Status = 5
)

var Status_name = map[int32]string{
	0: "STATUS_UNREGISTERED",
	1: "STATUS_REGISTERED",
	2: "STATUS_PUBLISHED",
	3: "STATUS_ARCHIVED",
	4: "STATUS_TEMPORARY_RESTORED",
	5: "STATUS_SUSPENDED",
}

var Status_value = map[string]int32{
	"STATUS_UNREGISTERED":       0,
	"STATUS_REGISTERED":         1,
	"STATUS_PUBLISHED":          2,
	"STATUS_ARCHIVED":           3,
	"STATUS_TEMPORARY_RESTORED": 4,
	"STATUS_SUSPENDED":          5,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83e5cd47fcaaecba, []int{1}
}

// A video information.
type Video struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VideoUrl             string               `protobuf:"bytes,2,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Thumbnail            *v1.Thumbnail        `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Title                string               `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Category             Category             `protobuf:"varint,6,opt,name=category,proto3,enum=gonpe.video.v1.Category" json:"category,omitempty"`
	Status               Status               `protobuf:"varint,7,opt,name=status,proto3,enum=gonpe.video.v1.Status" json:"status,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,8,opt,name=duration,proto3" json:"duration,omitempty"`
	FileSizeBytes        int64                `protobuf:"varint,9,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	RecordedAt           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Video) Reset()         { *m = Video{} }
func (m *Video) String() string { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()    {}
func (*Video) Descriptor() ([]byte, []int) {
	return fileDescriptor_83e5cd47fcaaecba, []int{0}
}

func (m *Video) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Video.Unmarshal(m, b)
}
func (m *Video) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Video.Marshal(b, m, deterministic)
}
func (m *Video) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Video.Merge(m, src)
}
func (m *Video) XXX_Size() int {
	return xxx_messageInfo_Video.Size(m)
}
func (m *Video) XXX_DiscardUnknown() {
	xxx_messageInfo_Video.DiscardUnknown(m)
}

var xxx_messageInfo_Video proto.InternalMessageInfo

func (m *Video) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Video) GetVideoUrl() string {
	if m != nil {
		return m.VideoUrl
	}
	return ""
}

func (m *Video) GetThumbnail() *v1.Thumbnail {
	if m != nil {
		return m.Thumbnail
	}
	return nil
}

func (m *Video) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Video) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Video) GetCategory() Category {
	if m != nil {
		return m.Category
	}
	return Category_CATEGORY_UNKNOWN
}

func (m *Video) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_STATUS_UNREGISTERED
}

func (m *Video) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Video) GetFileSizeBytes() int64 {
	if m != nil {
		return m.FileSizeBytes
	}
	return 0
}

func (m *Video) GetRecordedAt() *timestamp.Timestamp {
	if m != nil {
		return m.RecordedAt
	}
	return nil
}

// A video information for list display.
type VideoForList struct {
	Url                  string               `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Thumbnail            *v1.Thumbnail        `protobuf:"bytes,2,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category             Category             `protobuf:"varint,5,opt,name=category,proto3,enum=gonpe.video.v1.Category" json:"category,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	RecordedAt           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VideoForList) Reset()         { *m = VideoForList{} }
func (m *VideoForList) String() string { return proto.CompactTextString(m) }
func (*VideoForList) ProtoMessage()    {}
func (*VideoForList) Descriptor() ([]byte, []int) {
	return fileDescriptor_83e5cd47fcaaecba, []int{1}
}

func (m *VideoForList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoForList.Unmarshal(m, b)
}
func (m *VideoForList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoForList.Marshal(b, m, deterministic)
}
func (m *VideoForList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoForList.Merge(m, src)
}
func (m *VideoForList) XXX_Size() int {
	return xxx_messageInfo_VideoForList.Size(m)
}
func (m *VideoForList) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoForList.DiscardUnknown(m)
}

var xxx_messageInfo_VideoForList proto.InternalMessageInfo

func (m *VideoForList) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *VideoForList) GetThumbnail() *v1.Thumbnail {
	if m != nil {
		return m.Thumbnail
	}
	return nil
}

func (m *VideoForList) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *VideoForList) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *VideoForList) GetCategory() Category {
	if m != nil {
		return m.Category
	}
	return Category_CATEGORY_UNKNOWN
}

func (m *VideoForList) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *VideoForList) GetRecordedAt() *timestamp.Timestamp {
	if m != nil {
		return m.RecordedAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("gonpe.video.v1.Category", Category_name, Category_value)
	proto.RegisterEnum("gonpe.video.v1.Status", Status_name, Status_value)
	proto.RegisterType((*Video)(nil), "gonpe.video.v1.Video")
	proto.RegisterType((*VideoForList)(nil), "gonpe.video.v1.VideoForList")
}

func init() { proto.RegisterFile("gonpe/video/v1/video.proto", fileDescriptor_83e5cd47fcaaecba) }

var fileDescriptor_83e5cd47fcaaecba = []byte{
	// 710 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xdf, 0x6e, 0xda, 0x48,
	0x18, 0xc5, 0x63, 0x9b, 0xbf, 0x1f, 0x09, 0x99, 0x4c, 0xb2, 0x59, 0x27, 0xab, 0xdd, 0x45, 0xb9,
	0x58, 0xa1, 0x5c, 0x18, 0x91, 0xdd, 0xd5, 0x5e, 0xec, 0x95, 0xc1, 0x13, 0xb0, 0x1a, 0x6c, 0x34,
	0x1e, 0x93, 0x52, 0x45, 0x42, 0xfc, 0x71, 0xa8, 0x25, 0x88, 0x91, 0x31, 0x48, 0xc9, 0x93, 0xf4,
	0xba, 0x37, 0x95, 0xfa, 0x04, 0x95, 0xfa, 0x06, 0x7d, 0xaa, 0xca, 0x63, 0xe3, 0x62, 0x2a, 0x45,
	0x69, 0xef, 0xf0, 0xef, 0x1c, 0xcf, 0xf7, 0x71, 0xce, 0x18, 0xce, 0xa7, 0xde, 0xc3, 0xc2, 0xa9,
	0xad, 0xdd, 0x89, 0xe3, 0xd5, 0xd6, 0xf5, 0xe8, 0x87, 0xb2, 0xf0, 0xbd, 0xc0, 0xc3, 0x65, 0xae,
	0x29, 0x11, 0x5a, 0xd7, 0xcf, 0xff, 0x88, 0xbc, 0xee, 0x7c, 0x38, 0x75, 0x42, 0x6f, 0xf0, 0x76,
	0x35, 0x1f, 0x3d, 0x0c, 0xdd, 0x59, 0xe4, 0x0f, 0x75, 0x6f, 0x3a, 0x73, 0x6a, 0xfc, 0x69, 0xb4,
	0xba, 0xaf, 0x4d, 0x56, 0xfe, 0x30, 0x70, 0xbd, 0x87, 0x58, 0xff, 0x73, 0x57, 0x0f, 0xdc, 0xb9,
	0xb3, 0x0c, 0x86, 0xf3, 0x45, 0x64, 0xb8, 0xf8, 0x20, 0x41, 0xb6, 0x17, 0x4e, 0xc3, 0x65, 0x10,
	0xdd, 0x89, 0x2c, 0x54, 0x84, 0x6a, 0x91, 0x8a, 0xee, 0x04, 0xff, 0x06, 0x45, 0xbe, 0xc6, 0x60,
	0xe5, 0xcf, 0x64, 0x91, 0xe3, 0x02, 0x07, 0xb6, 0x3f, 0xc3, 0xff, 0x41, 0x31, 0x59, 0x45, 0x96,
	0x2a, 0x42, 0xb5, 0x74, 0x75, 0xa6, 0x44, 0xbb, 0xf3, 0x5d, 0x95, 0x75, 0x5d, 0x61, 0x1b, 0x03,
	0xfd, 0xe6, 0xc5, 0x27, 0x90, 0x0d, 0xdc, 0x60, 0xe6, 0xc8, 0x19, 0x7e, 0x62, 0xf4, 0x80, 0x2b,
	0x50, 0x9a, 0x38, 0xcb, 0xb1, 0xef, 0x2e, 0xc2, 0xdd, 0xe5, 0x2c, 0xd7, 0xb6, 0x11, 0xfe, 0x07,
	0x0a, 0xe3, 0x61, 0xe0, 0x4c, 0x3d, 0xff, 0x51, 0xce, 0x55, 0x84, 0x6a, 0xf9, 0x4a, 0x56, 0xd2,
	0x59, 0x29, 0xcd, 0x58, 0xa7, 0x89, 0x13, 0x2b, 0x90, 0x5b, 0x06, 0xc3, 0x60, 0xb5, 0x94, 0xf3,
	0xfc, 0x9d, 0xd3, 0xdd, 0x77, 0x2c, 0xae, 0xd2, 0xd8, 0x85, 0xff, 0x85, 0xc2, 0x26, 0x40, 0xb9,
	0x90, 0xfc, 0xab, 0x30, 0x41, 0x65, 0x93, 0xa0, 0xa2, 0xc5, 0x06, 0x9a, 0x58, 0xf1, 0x5f, 0x70,
	0x78, 0xef, 0xce, 0x9c, 0xc1, 0xd2, 0x7d, 0x72, 0x06, 0xa3, 0xc7, 0xc0, 0x59, 0xca, 0xc5, 0x8a,
	0x50, 0x95, 0xe8, 0x41, 0x88, 0x2d, 0xf7, 0xc9, 0x69, 0x84, 0x10, 0xff, 0x0f, 0x25, 0xdf, 0x19,
	0x7b, 0xfe, 0xc4, 0x99, 0x0c, 0x86, 0x81, 0x0c, 0x7c, 0xc2, 0xf9, 0x77, 0x13, 0xd8, 0xa6, 0x23,
	0x0a, 0x1b, 0xbb, 0x1a, 0x5c, 0x7c, 0x16, 0x61, 0x9f, 0x37, 0x75, 0xed, 0xf9, 0x37, 0xee, 0x32,
	0xc0, 0x08, 0xa4, 0xb0, 0x9a, 0xa8, 0xb1, 0xf0, 0x67, 0xba, 0x15, 0xf1, 0x67, 0x5a, 0x91, 0x9e,
	0x69, 0x25, 0xf3, 0x7c, 0x2b, 0xd9, 0x17, 0xb7, 0xb2, 0x9d, 0x72, 0xee, 0xe5, 0x29, 0xef, 0xa4,
	0x97, 0xff, 0x91, 0xf4, 0x2e, 0x3f, 0x89, 0x50, 0xd8, 0xac, 0x82, 0x4f, 0x00, 0x35, 0x55, 0x46,
	0x5a, 0x26, 0xed, 0x0f, 0x6c, 0xe3, 0x95, 0x61, 0xde, 0x1a, 0x68, 0x0f, 0x9f, 0x02, 0x4e, 0xa8,
	0x6a, 0xe8, 0x1d, 0x95, 0xe9, 0xa6, 0x81, 0x04, 0x8c, 0xa1, 0x9c, 0xf0, 0x8e, 0x6d, 0xe9, 0x4d,
	0x24, 0xa6, 0x4e, 0xe8, 0xa9, 0x54, 0x27, 0xac, 0x8f, 0xa4, 0x94, 0x53, 0xa3, 0x6a, 0x47, 0x45,
	0x19, 0x7c, 0x0c, 0x87, 0x09, 0x6b, 0xea, 0x06, 0xe9, 0xa8, 0x28, 0x9b, 0x32, 0x5a, 0x5d, 0x93,
	0x32, 0x94, 0xc3, 0x32, 0x9c, 0x24, 0x4c, 0x37, 0xae, 0x4d, 0x1a, 0x2f, 0x90, 0xc7, 0x47, 0x70,
	0x90, 0x28, 0x06, 0xb9, 0xb5, 0x50, 0x21, 0x65, 0xd6, 0xcc, 0xa6, 0xdd, 0x21, 0x06, 0x53, 0x69,
	0x1f, 0x15, 0x53, 0x9b, 0xb1, 0x36, 0x51, 0x19, 0xa1, 0x08, 0x52, 0x03, 0xdb, 0x66, 0xa3, 0xd1,
	0x47, 0xa5, 0x94, 0xf3, 0x96, 0xdc, 0x5c, 0xab, 0x94, 0xa0, 0x7d, 0x8c, 0x60, 0x3f, 0xa1, 0x84,
	0x35, 0xd1, 0xc1, 0xe5, 0x3b, 0x01, 0x72, 0xd1, 0x77, 0x82, 0x7f, 0x85, 0x63, 0x8b, 0xa9, 0xcc,
	0xb6, 0x06, 0xb6, 0x41, 0x49, 0x4b, 0xb7, 0x18, 0xa1, 0x44, 0x43, 0x7b, 0xf8, 0x17, 0x38, 0x8a,
	0x85, 0x2d, 0x2c, 0x84, 0x23, 0x62, 0xdc, 0xb5, 0x1b, 0x37, 0xba, 0xd5, 0x26, 0x1a, 0x12, 0xc3,
	0x48, 0x62, 0xaa, 0xd2, 0x66, 0x5b, 0xef, 0x11, 0x0d, 0x49, 0xf8, 0x77, 0x38, 0x8b, 0x21, 0x23,
	0x9d, 0xae, 0x49, 0x55, 0xda, 0x1f, 0x50, 0x62, 0x31, 0x33, 0x3c, 0x29, 0xb3, 0x75, 0x92, 0x65,
	0x5b, 0x5d, 0x62, 0x68, 0x44, 0x43, 0xd9, 0x86, 0x05, 0x78, 0xec, 0xcd, 0x77, 0xae, 0x5c, 0x03,
	0xf8, 0x67, 0xd2, 0x0d, 0x2f, 0x44, 0x57, 0x78, 0x93, 0xe7, 0x7c, 0x5d, 0x7f, 0x2f, 0x4a, 0xad,
	0xde, 0xeb, 0x8f, 0x62, 0xb9, 0xc5, 0xdd, 0xdc, 0xa3, 0xf4, 0xea, 0x5f, 0x62, 0x70, 0xc7, 0xc1,
	0x5d, 0xaf, 0x3e, 0xca, 0xf1, 0xab, 0xf4, 0xf7, 0xd7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x95,
	0x7b, 0xef, 0xa8, 0x05, 0x00, 0x00,
}
