// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gonpe/video/v1/video_api.proto

package videov1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRecentlyVideosRequest struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              int64    `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRecentlyVideosRequest) Reset()         { *m = ListRecentlyVideosRequest{} }
func (m *ListRecentlyVideosRequest) String() string { return proto.CompactTextString(m) }
func (*ListRecentlyVideosRequest) ProtoMessage()    {}
func (*ListRecentlyVideosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4a7caa6426bdf00, []int{0}
}

func (m *ListRecentlyVideosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecentlyVideosRequest.Unmarshal(m, b)
}
func (m *ListRecentlyVideosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecentlyVideosRequest.Marshal(b, m, deterministic)
}
func (m *ListRecentlyVideosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecentlyVideosRequest.Merge(m, src)
}
func (m *ListRecentlyVideosRequest) XXX_Size() int {
	return xxx_messageInfo_ListRecentlyVideosRequest.Size(m)
}
func (m *ListRecentlyVideosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecentlyVideosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecentlyVideosRequest proto.InternalMessageInfo

func (m *ListRecentlyVideosRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRecentlyVideosRequest) GetPerPage() int64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

type ListRecentlyVideosResponse struct {
	Videos               []*Video `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	ExistPrev            bool     `protobuf:"varint,3,opt,name=exist_prev,json=existPrev,proto3" json:"exist_prev,omitempty"`
	ExistNext            bool     `protobuf:"varint,4,opt,name=exist_next,json=existNext,proto3" json:"exist_next,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRecentlyVideosResponse) Reset()         { *m = ListRecentlyVideosResponse{} }
func (m *ListRecentlyVideosResponse) String() string { return proto.CompactTextString(m) }
func (*ListRecentlyVideosResponse) ProtoMessage()    {}
func (*ListRecentlyVideosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4a7caa6426bdf00, []int{1}
}

func (m *ListRecentlyVideosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecentlyVideosResponse.Unmarshal(m, b)
}
func (m *ListRecentlyVideosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecentlyVideosResponse.Marshal(b, m, deterministic)
}
func (m *ListRecentlyVideosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecentlyVideosResponse.Merge(m, src)
}
func (m *ListRecentlyVideosResponse) XXX_Size() int {
	return xxx_messageInfo_ListRecentlyVideosResponse.Size(m)
}
func (m *ListRecentlyVideosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecentlyVideosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecentlyVideosResponse proto.InternalMessageInfo

func (m *ListRecentlyVideosResponse) GetVideos() []*Video {
	if m != nil {
		return m.Videos
	}
	return nil
}

func (m *ListRecentlyVideosResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListRecentlyVideosResponse) GetExistPrev() bool {
	if m != nil {
		return m.ExistPrev
	}
	return false
}

func (m *ListRecentlyVideosResponse) GetExistNext() bool {
	if m != nil {
		return m.ExistNext
	}
	return false
}

func init() {
	proto.RegisterType((*ListRecentlyVideosRequest)(nil), "gonpe.video.v1.ListRecentlyVideosRequest")
	proto.RegisterType((*ListRecentlyVideosResponse)(nil), "gonpe.video.v1.ListRecentlyVideosResponse")
}

func init() { proto.RegisterFile("gonpe/video/v1/video_api.proto", fileDescriptor_c4a7caa6426bdf00) }

var fileDescriptor_c4a7caa6426bdf00 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0xa6, 0xb6, 0x75, 0xc4, 0x1e, 0x16, 0x85, 0x34, 0xa0, 0x94, 0x9e, 0xaa, 0xe0,
	0x96, 0xd4, 0x27, 0xb0, 0x97, 0xa2, 0x88, 0x84, 0x1c, 0x82, 0x48, 0x21, 0xc4, 0x38, 0x84, 0xa0,
	0x66, 0xd7, 0xec, 0x76, 0x8d, 0x4f, 0x23, 0x78, 0xf4, 0x51, 0x7c, 0x2a, 0xe9, 0x24, 0xa0, 0xd6,
	0x0a, 0xde, 0x66, 0xff, 0xff, 0x9b, 0x9d, 0x7f, 0x77, 0xe0, 0x30, 0x93, 0x85, 0xc2, 0x89, 0xcd,
	0xef, 0x50, 0x4e, 0xac, 0x5f, 0x17, 0x71, 0xa2, 0x72, 0xa1, 0x4a, 0x69, 0x24, 0xef, 0x93, 0x2f,
	0x48, 0x16, 0xd6, 0xf7, 0xbc, 0x4d, 0x7c, 0xcd, 0x8e, 0x2e, 0x60, 0x70, 0x99, 0x6b, 0x13, 0x62,
	0x8a, 0x85, 0x79, 0x78, 0x89, 0x56, 0x96, 0x0e, 0xf1, 0x69, 0x89, 0xda, 0x70, 0x0e, 0x6d, 0x95,
	0x64, 0xe8, 0xb2, 0x21, 0x1b, 0x3b, 0x21, 0xd5, 0x7c, 0x00, 0x3d, 0x85, 0x65, 0x4c, 0x7a, 0x8b,
	0xf4, 0xae, 0xc2, 0x32, 0x48, 0x32, 0x1c, 0xbd, 0x32, 0xf0, 0x36, 0x5d, 0xa6, 0x95, 0x2c, 0x34,
	0xf2, 0x13, 0xe8, 0xd0, 0x64, 0xed, 0xb2, 0xa1, 0x33, 0xde, 0x99, 0xee, 0x8b, 0x9f, 0x39, 0x05,
	0xf1, 0x61, 0x03, 0xf1, 0x3d, 0xd8, 0x4a, 0xe5, 0xb2, 0x30, 0xcd, 0x94, 0xfa, 0xc0, 0x0f, 0x00,
	0xb0, 0xca, 0xb5, 0x89, 0x55, 0x89, 0xd6, 0x75, 0x86, 0x6c, 0xdc, 0x0b, 0xb7, 0x49, 0x09, 0x4a,
	0xb4, 0x5f, 0x76, 0x81, 0x95, 0x71, 0xdb, 0xdf, 0xec, 0x2b, 0xac, 0xcc, 0xf4, 0x19, 0x7a, 0x34,
	0xe4, 0x2c, 0x38, 0xe7, 0xf7, 0xc0, 0x7f, 0x87, 0xe5, 0x47, 0xeb, 0xa1, 0xfe, 0xfc, 0x1d, 0xef,
	0xf8, 0x3f, 0x68, 0xfd, 0xf6, 0x59, 0x04, 0x3c, 0x95, 0x8f, 0x6b, 0x0d, 0xb3, 0xdd, 0x3a, 0x8c,
	0xca, 0x83, 0xd5, 0x2e, 0x02, 0x76, 0xd3, 0x25, 0xcb, 0xfa, 0x6f, 0x2d, 0x67, 0x1e, 0x5d, 0xbf,
	0xb7, 0xfa, 0x73, 0x6a, 0x20, 0x4c, 0x44, 0xfe, 0x47, 0x23, 0x2c, 0x48, 0x58, 0x44, 0xfe, 0x6d,
	0x87, 0xb6, 0x78, 0xfa, 0x19, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x3b, 0xd2, 0x0d, 0x13, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VideoAPIClient is the client API for VideoAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VideoAPIClient interface {
	// Get videos in descending order of recording at.
	ListRecentlyVideos(ctx context.Context, in *ListRecentlyVideosRequest, opts ...grpc.CallOption) (*ListRecentlyVideosResponse, error)
}

type videoAPIClient struct {
	cc *grpc.ClientConn
}

func NewVideoAPIClient(cc *grpc.ClientConn) VideoAPIClient {
	return &videoAPIClient{cc}
}

func (c *videoAPIClient) ListRecentlyVideos(ctx context.Context, in *ListRecentlyVideosRequest, opts ...grpc.CallOption) (*ListRecentlyVideosResponse, error) {
	out := new(ListRecentlyVideosResponse)
	err := c.cc.Invoke(ctx, "/gonpe.video.v1.VideoAPI/ListRecentlyVideos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoAPIServer is the server API for VideoAPI service.
type VideoAPIServer interface {
	// Get videos in descending order of recording at.
	ListRecentlyVideos(context.Context, *ListRecentlyVideosRequest) (*ListRecentlyVideosResponse, error)
}

func RegisterVideoAPIServer(s *grpc.Server, srv VideoAPIServer) {
	s.RegisterService(&_VideoAPI_serviceDesc, srv)
}

func _VideoAPI_ListRecentlyVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecentlyVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoAPIServer).ListRecentlyVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gonpe.video.v1.VideoAPI/ListRecentlyVideos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoAPIServer).ListRecentlyVideos(ctx, req.(*ListRecentlyVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VideoAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gonpe.video.v1.VideoAPI",
	HandlerType: (*VideoAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRecentlyVideos",
			Handler:    _VideoAPI_ListRecentlyVideos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gonpe/video/v1/video_api.proto",
}
