// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gonpe/auth/v1/auth_api.proto

package authv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignUpRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6733bab8db929af9, []int{0}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SignUpResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6733bab8db929af9, []int{1}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SignUpRequest)(nil), "gonpe.auth.v1.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "gonpe.auth.v1.SignUpResponse")
}

func init() { proto.RegisterFile("gonpe/auth/v1/auth_api.proto", fileDescriptor_6733bab8db929af9) }

var fileDescriptor_6733bab8db929af9 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0xcf, 0xcf, 0x2b,
	0x48, 0xd5, 0x4f, 0x2c, 0x2d, 0xc9, 0xd0, 0x2f, 0x33, 0x04, 0xd3, 0xf1, 0x89, 0x05, 0x99, 0x7a,
	0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xbc, 0x60, 0x59, 0x3d, 0x90, 0xa8, 0x5e, 0x99, 0xa1, 0x92,
	0x2a, 0x17, 0x6f, 0x70, 0x66, 0x7a, 0x5e, 0x68, 0x41, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89,
	0x90, 0x08, 0x17, 0x6b, 0x6a, 0x6e, 0x62, 0x66, 0x8e, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10,
	0x84, 0xa3, 0x24, 0xc0, 0xc5, 0x07, 0x53, 0x56, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x6a, 0x14, 0xc0,
	0xc5, 0xee, 0x58, 0x5a, 0x92, 0xe1, 0x18, 0xe0, 0x29, 0xe4, 0xca, 0xc5, 0x06, 0x91, 0x14, 0x92,
	0xd1, 0x43, 0x31, 0x5d, 0x0f, 0xc5, 0x68, 0x29, 0x59, 0x1c, 0xb2, 0x10, 0x13, 0x9d, 0x02, 0xb9,
	0x04, 0x93, 0xf3, 0x73, 0x51, 0xd5, 0x38, 0xf1, 0x80, 0x2d, 0x29, 0xc8, 0x0c, 0x00, 0x39, 0x3e,
	0x80, 0x31, 0x8a, 0x0d, 0x24, 0x51, 0x66, 0xb8, 0x88, 0x89, 0xd9, 0xdd, 0x31, 0x62, 0x15, 0x13,
	0xaf, 0x3b, 0x58, 0x35, 0x48, 0x91, 0x5e, 0x98, 0xe1, 0x29, 0x28, 0x3f, 0x06, 0xc4, 0x8f, 0x09,
	0x33, 0x4c, 0x62, 0x03, 0xfb, 0xd9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x10, 0xde, 0xdc, 0x3e,
	0x13, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthAPIClient is the client API for AuthAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthAPIClient interface {
	// Registration user.
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
}

type authAPIClient struct {
	cc *grpc.ClientConn
}

func NewAuthAPIClient(cc *grpc.ClientConn) AuthAPIClient {
	return &authAPIClient{cc}
}

func (c *authAPIClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, "/gonpe.auth.v1.AuthAPI/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthAPIServer is the server API for AuthAPI service.
type AuthAPIServer interface {
	// Registration user.
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
}

func RegisterAuthAPIServer(s *grpc.Server, srv AuthAPIServer) {
	s.RegisterService(&_AuthAPI_serviceDesc, srv)
}

func _AuthAPI_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthAPIServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gonpe.auth.v1.AuthAPI/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthAPIServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gonpe.auth.v1.AuthAPI",
	HandlerType: (*AuthAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _AuthAPI_SignUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gonpe/auth/v1/auth_api.proto",
}
